GET http://localhost:3310/api/recipes/3

###

POST http://localhost:3310/api/recipe/create HTTP/1.1
content-type: application/json

  {
    "title": "Omelette au jambon",
    "picture": "omelette.jpg",
    "nb_parts": 4,
    "is_published":0,
    "time_to_cook": 10,
    "preparation_time": 45,
    "ingredients_list": [
      {
        "id": 1,
        "measure": "pièce",
        "quantity": 6
      },
      {
        "id": 4,
        "measure": "tranches",
        "quantity": 3
      }
    ]
  }


### 

GET http://localhost:3310/api/ingredients

###

POST http://localhost:3310/api/ingredients HTTP/1.1
content-type: application/json

  {
    "name_ingredient": "Pâte à tarte",
    "picture_ingredient": "https://media.istockphoto.com/id/500803741/fr/photo/faire-cuire-les-ingr%C3%A9dients-p%C3%A2te-et-le-rouleau-%C3%A0-p%C3%A2tisserie.jpg?s=612x612&w=0&k=20&c=gdy8JWORE41o-gPqpU6oY_roA957OYoKpRSSs7xAnhY="
  }